### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Aatch** [Hoverbear/rust-education-paper#10]
Some feedback and suggestions:
## Section 2.1

  I'm not sure Rust has much syntactic similarity to ML. Other than the use of 'let'.
  Probably just a short "The syntax of Rust should be familiar to most programmers:
  <example>" will do.

  The part about function definitions seems out of place. It's unclear how it relates to
  common problems encountered by students.
## Section 2.2

  Could probably do with some re-working to focus on the link between "Strong Type System"
  and "prevents common bugs". As it is now, you jump straight into "You can still do those
  things in Rust". It's not clear _how_ Rust prevents the mistakes you mention in the first
  paragraph, you just say that it does.
## Section 4

  I'm not sure the assumption in the first paragraph is particularly valid. I think it
  either needs to be sourced, or removed altogether.

  The comparisons to C/C++ could be done more concicely: "In some ways Rust's memory model
  is similar to C/C++'s: <similarities>. However, Rust introduces several distinctions:
  <distinctions>".
## Section 5

  I think mentioning Java and C++ here is unnecessary. You can talk about interfaces in
  general terms. More specifically, you can say something like "traits define a common
  interface that can be implemented by many different types".

  The reference to "UNIX philosphy" seems unnecessary. Just say that they encourage code-
  reuse via composition rather than inheritance. The mention of state machines is also not
  adding much.
## Section 7

  Final paragraph, discussion of the stability of an API seems unnecessary. Just mention
  that it is possible to safely share stack-allocated data across threads using the
  features Rust provides.

**Comment by Hoverbear** [comment]
Thanks for your feedback @Aatch! I've integrated much of it!

## Section 2.1
- Fixed ML part.
- I wanted to include the differing function definitions because of the cited article about function declaration and how C's is insufficient.

## Section 2.2
- You're right. We used to have another example in that section but cut it for space.

## Section 4
- Yup, I agree! Reworked a bit.

## Section 5
- You're right about the UNIX thing.
- The mention of markers was mentioned in the introduction as a way to mark "Tainted data", so I think it should be left in.

## Section 7
- Yup!
